apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs-static
  labels:
    project: expense
    env: dev
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e1581e636b0f257e
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs-static-claim
  labels:
    project: expense
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: expense-efs-static
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-pod
  labels:
    project: expense
    environment: dev
spce:
  containers:
  - name: expense-cont
    image: nginx
    volumeMounts:
    - name: expense-efs-static
      mountPath: /usr/share/nginx/html/
volumes:
- name: expense-efs-static
  persistentVolumeClaim:
    claimName: expense-efs-static-claim
---
apiversion: v1
kind: Service
metadata:
  name: efs-service
  labels:
    project: expense
    environment: dev
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
  ports:
  - name: nginx-service-port
    protocol: TCP
    port: 80
    targetPort: 80

