apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0e1581e636b0f257e
  directoryPerms: "700"
  basePath: "/expense"
  volumeBindingMode: 
