apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
  labels:
    project: expense
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: expense-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
  labels:
    project: demo
    env: QA
spec:
  containers:
  - name: dynamic-cont
    image: nginx
    volumeMounts:
    - name: dynamic-pvc
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: dynamic-pvc
    persistentVolumeClaim:
      claimName: dynamic-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-service
  labels:
    project: test
spec:
  type: LoadBalancer
  selector:
    project: demo
    env: QA
  ports:
  - name: test-port
    protocol: TCP
    port: 80
    targetPort: 80