kind: Pod
apiVersion: v1
metadata:
  name: expense-1
  labels:
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep 100"]