apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  namespace: expense
  labels:
    environment: dev
    project: expense
    module: backend
spec:
  containers:
  - name: nginx-label
    image: nginx