apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  namespace: expense
  labels:
    environment: dev
  annotations:
    projecct: expense
    module: backend
spec:
  containers:
  - name: maxdep
    image: nginx
    env:
    - name: course
      value: devops
    - name: duration
      value: 120hrs
    - name: train
      value: howrah
