apiVersion: v1
kind: Pod
metadata:
  name: rescue
  namespace: expense
  labels:
    environment: dev
  annotations:
    module: backend
    project: expense
spec:
  containers:
  - name: brex
    image: nginx
    env:
    - name: course
      value: devops
    - name: duration
      value: 102 hrs
    resources:
      requests:
        cpu: 100m
        memory: 70Mi
      limits:
        cpu: 170m
        memory: 100Mi