kind: Pod
apiVersion: v1
metadata:
  name: dragon
  labels:
    environment: dev
  annotations:
    gitlink: https://github.com/Amarnadh31/k8s-resources.git
spec:
  containers:
  - name: temp
    image: almalinux:9
    command: ["sleep", "1000"]
    envFrom:
    - configMapRef:
        name: demo-conf
    # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: demo-conf
    #       key: branch
    # - name: duration
    #   valueFrom:
    #     configMapKeyRef:
    #       name: demo-conf
    #       key: institute