kind: Pod
apiVersion: v1
metadata:
  name: pod-mad
  labels:
    environment: dev
spec:
  containers:
  - name: intro
    image: almalinux:9
    envFrom:
    - configMapRef:
        name: demo-conf
    - secretRef:
        name: pod-secret