apiVersion: v1
kind: Service
metadata:
  name: clusterIP
spec:
  selector:
    environment: dev
  ports:
  - name: nginx-service-port
    protocol: tcp
    port: 80 #service port
    targetport: 80 #container port
 