apiVersion: v1
kind: Pod
metadata:
  name: rep-pod
  labels:
    environment: dev
    project: expense
    module: prod
spec:
  containers:
    - name: normal
      image: almalinux:9
      command: ["sleep","10000"]