apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
  labels:
    project: defense
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabel:
      environment: dev
      project: expense
      module: prod
  template:
    metadata:
      labels:
        environment: dev
        project: expense
        module: prod
    spec:
     containers:
     - name: nginx
       image: nginx

      
  