apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: secretaccount
  namespace: expense
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: secretuser
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secretuser
  namespace: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secretuser
subjects:
- kind: ServiceAccount
  name: secretaccount
  namespace: expense
---
apiVersion: v1
kind: Pod
metadata:
  name: dream
  namespace: expense
  labels:
    project: expense
spec:

  serviceAccountName: secretaccount
  containers:
  #docker run -d --name naginx nginx
  - name: nginx
    image: nginx
